### ISSUE TITLE
missing type_switch

### ISSUE THREAD

**Issue by viboes** [mpark/variant#1]
Hi Michael, I was looking for `type_switch` and I was unable to find it. Have you implemented it?

**Comment by mpark** [comment]
Hi @viboes, I had `type_switch` before when I was implementing [P00080R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0080r0.pdf). Since I'm now implementing the Kona `variant`, I've implemented `visit` instead.

**Comment by viboes** [comment]
Could you point me to your old implementation of type_switch? In which file it was?

Vicente Botet

**Comment by mpark** [comment]
The P0080R0 implementation is at [this commit](https://github.com/mpark/variant/tree/f61d6b2903f73064285fc24686db0282560eea02). The `type_switch` in specific is [here]( https://github.com/mpark/variant/blob/f61d6b2903f73064285fc24686db0282560eea02/include/mpark/variant/type_switch.hpp).

**Comment by viboes** [comment]
Thanks. I don't see how the customization is done? neither where dispatch is defined.

**Comment by mpark** [comment]
@viboes: I didn't go as far as to introduce a generalized `type_switch` like your `match` in [P0050R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0050r0.pdf). My focus was on exploring what the `type_switch` syntax would look like, and which `variant` specific parts will need to be supported.

**Comment by viboes** [comment]
No problem. I was curious to see your implementation.
