### ISSUE TITLE
Warning: implicit conversion loses integer precision

### ISSUE THREAD

**Issue by jfirebaugh** [mpark/variant#23]
When compiling with `-Wshorten-64-to-32` on platforms where `std::size_t` is `unsigned long`, many warnings of the following form are produced:

```
include/mpark/variant.hpp:754:24: warning: implicit conversion loses integer precision: 'std::size_t' (aka 'unsigned long') to 'unsigned int' [-Wshorten-64-to-32]
          lhs.index_ = rhs.index();
                     ~ ^~~~~~~~~~~
```

**Comment by viboes** [comment]
Could you give more context so that we know what lhs and rhs are?

**Comment by jfirebaugh** [comment]
Sure --  as far as I can tell (not super familiar with the implementation), this warning will occur regardless of the alternative types of the actual `variant` in use, because the `lhs` and `rhs` involved here are internal to the implementation. The error location is [here](https://github.com/mpark/variant/blob/6bae888c3a8eb19a3bbec76b1453e682439a2eac/include/mpark/variant.hpp#L754), so:

* `lhs` is `mpark::detail::constructor<Traits>` and `lhs.index_` is [`unsigned int index_` from `base`](https://github.com/mpark/variant/blob/6bae888c3a8eb19a3bbec76b1453e682439a2eac/include/mpark/variant.hpp#L673)
* the type of `rhs` is a templated type, but I'm guessing it's also some instantation of `base`, meaning `rhs.index()` is [`base::index()`](https://github.com/mpark/variant/blob/6bae888c3a8eb19a3bbec76b1453e682439a2eac/include/mpark/variant.hpp#L660), returning `std::size_t`.

**Comment by mpark** [comment]
Fixed in https://github.com/mpark/variant/commit/d8fd0fbba727f0f2f757a05ae7a86e14c3b5982c
