### ISSUE TITLE
`#include` relative headers

### ISSUE THREAD

**Issue by mpark** [mpark/variant#29]
or even just provide a single header

**Comment by viboes** [comment]
why do you believe it is better to have relative headers. I'm all for absolute headers and would like to know why I'm wrong.

**Comment by mpark** [comment]
@viboes: Is #31 convincing enough to you? /cc @pdimov
But I'm actually leaning towards providing a single header. It seems like it would be the most convenient for people

**Comment by pdimov** [comment]
#31 basically explains it. The idea is to have it work when `variant.hpp` is included, without the `-I` being necessary.
