### ISSUE TITLE
Add support for compilation with exceptions disabled

### ISSUE THREAD

**Issue by gcardwel** [mpark/variant#30]
If compiler support for exceptions is turned off, usually via `-fno-exceptions` command line switch on `gcc`/`clang`, then `std::variant` can never be in the `valueless_by_exception` state.   Thus, you should then be able to call `std::visit<>()` or `std::get<>()` without them doing the test for empty or having them call `throw`.  

As it stands now, you can't compile `variant` without having exception support enabled.

**Comment by mpark** [comment]
Closed by https://github.com/mpark/variant/commit/840f86b1f47275eb03c7f0d068d9eefc1774e3ab
