### ISSUE TITLE
Backport to GCC 4.8

### ISSUE THREAD

**Issue by mpark** [mpark/variant#37]

**Comment by tzlaine** [comment]
ETA?  Would it help to prod you on this if I told you I just recommended this implementation to some at-risk youths who are forced to use GCC 4.8.3?

**Comment by mpark** [comment]
Hi Zach! I'm planning to work on this next week. Last time I tried this it was having trouble with
the cartesian product generation here: https://github.com/mpark/variant/blob/master/include/mpark/variant.hpp#L574-L575

So I'll have to figure out how to deal with that part.
Appreciate  the recommendation!

**Comment by mpark** [comment]
Closed by 12b77f3325b81ba56a3c3f0b88e61b57505b9ff0.

The minimum repro of the problems were https://wandbox.org/permlink/ypmovjwyTaXnSnwy.
In short, `S<alias<pack..., thing>>` drops `thing` and incorrectly passes `alias<pack...>` instead.

This caused the `true` in `all` implementation to be dropped in `bool_sequence<Bs..., true>`,
and the `J` was dropped in `index_sequence<Is..., J>`. Since the issue was due to the fact that
`bool_sequence` and `index_sequence` are aliases, `integer_sequence` is now used directly.

**Comment by tzlaine** [comment]
Thanks for the quick resolution!
