### ISSUE TITLE
Issues packaging with conan.io

### ISSUE THREAD

**Issue by jgsogo** [mpark/variant#39]
Hi!

I'm trying to package this library (v1.3.0) using [conan.io](https://www.conan.io/), you can see my ongoing work in [this repo](https://github.com/jgsogo/conan-variant) and I want to share with you some issues I'm facing, just in case you have an opinion about them.

As the idea is to work with packaged dependencies, I am not using the `3rdparty` directory with the submodules but the `gtest` package provided by bincrafters (release-v1.8.0). Two comments when using this packaged library:
 * File [`internal_utils.cmake`](https://github.com/google/googletest/tree/release-1.8.0/googletest/cmake) is not packaged, so the function that is used [here](https://github.com/mpark/variant/blob/v1.3.0/test/CMakeLists.txt#L37) won't work. I've created another `gtest` package that export this file and included it, but I'm wondering if this file is intended to be used by packages depending on googletests or if it is just an internal one.
 * When you link against `gtest_main` [here](https://github.com/mpark/variant/blob/v1.3.0/test/CMakeLists.txt#L67) I have to link also against `gtest`, I've to check which one is the correct one.

If you are interested on having this library packaged with conan, I can work further on this and create a PR, otherwise I will keep using these workarounds. 

PD.- btw, I came to your library following the dependencies being used by spdlog_setup.

**Comment by mpark** [comment]
Thanks for the report and feedback!

I currently poke into the `internal_utils.cmake` file only because when I compile with no exceptions and such, as far as I understand gtest needs to be compiled with the same compiler flags as the tests themselves.

I don't think I understand exactly what the `gtest_main` / `gtest` problem is. Could you elaborate?

My plan ultimately is to switch over to use `Catch2` rather than `gtest`.

**Comment by jgsogo** [comment]
About `gtest_main`/`gtest`:

In `googletest` sources [here](https://github.com/google/googletest/blob/release-1.8.0/googletest/CMakeLists.txt#L90):

```
cxx_library(gtest "${cxx_strict}" src/gtest-all.cc)
cxx_library(gtest_main "${cxx_strict}" src/gtest_main.cc)
```

and watching the sources, `gtest` is the library itself and `gtest_main` is more like the executable (see [source for `gtest_main.cc`](https://github.com/google/googletest/blob/release-1.8.0/googletest/src/gtest_main.cc)).

**Comment by mpark** [comment]
I think I'll ditch gtest all-together shortly. Could you keep the workarounds for now and remove them once I ditch gtest?

**Comment by jgsogo** [comment]
Yes, of course. Just ping me when you release the new version.

Thanks!

**Comment by mpark** [comment]
@jgsogo: Closing for now. Will ping when I get around to ditching gtest.
