### ISSUE TITLE
Intellisense stop working in VS 2017 after including mpark/varaint.hpp

### ISSUE THREAD

**Issue by yujin-lai** [mpark/variant#47]
We've narrowed the issue to the lib.hpp file in mpark variant

These lines are messing up intellisense(Lines 393-397 in lib.hpp of mpark)

   template <std::size_t I, typename... Ts>
   using type_pack_element = typename type_pack_element_impl<I, Ts...>::type;

   template <std::size_t I, typename... Ts>
   using type_pack_element_t = typename type_pack_element<I, Ts...>::type;

Could you check it and fix it? you know, It's painful to work without intellisense.

**Comment by mpark** [comment]
@yujin-lai: Is this still an issue?

**Comment by mpark** [comment]
Ah okay. Sorry I couldn't address the issue for you earlier 😕
