### ISSUE TITLE
Add support for VS 2015.

### ISSUE THREAD

**Issue by mpark** [mpark/variant#5]

**Comment by mpark** [comment]
Investigated the feasibility of supporting VS 2015 Update 1. I think there are currently too many missing features to justify the energy required to support it. Will re-investigate when update 2 is released.

The following are a few features I'm waiting on.
* Variable templates
* C++14 `constexpr`
* Partial SFINAE

**Comment by os12** [comment]
BTW, VS2015/update1 shipped with Clang/C2. Your existing code might just compile... 

P.S. Unfortunately, given the amount of templated code in the headers, it would probably be an all-or-nothing deal. I.e. no joy in regular VS builds.

**Comment by mpark** [comment]
@os12 Yeah, I found some other projects that support VS with Clang/C2. Do you think that would be useful?

**Comment by os12** [comment]
Well, I want to move my Windows-based builds to Clang/C2 when it matures 
a bit (you know, when it builds Boost). I love the modern frontend and 
VS/intellisense combo... but, who knows how stable it will be.

As for your std::variant implementation - it would be wonderful to be 
able to pick it up. Hopefully the support will require minimal or even 
no work from you...

**Comment by mpark** [comment]
I've added support for `VS 2015` with `Clang/LLVM`. That is, via `clang-cl`.
I've also added CI on Windows via AppVeyor: https://ci.appveyor.com/project/mpark/variant
