### ISSUE TITLE
CMake: 1.4.0 version bump

### ISSUE THREAD

**Issue by ax3l** [mpark/variant#60]
Hi,

thanks a lot for this library! :sparkles: 

I think the latest release `1.4.0` forgot to bump the CMake version, it still points to `1.3.0`:
https://github.com/mpark/variant/blob/master/CMakeLists.txt

Can you maybe bump it for a `1.4.1` release?

**Comment by mpark** [comment]
Oh no! That's embarrassing. Thanks for pointing this out 😕

**Comment by ax3l** [comment]
@mpark are you planning a 0.4.1 release (with bumped version)? :)
