### ISSUE TITLE
c++17 and CI issue

### ISSUE THREAD

**Issue by GillianGrayson** [mpark/variant#62]
Hi! 
Thanks for sharing such useful lib!

I have a question about c++17 standard and your CI (Travis and Appveyor) settings.
In c++17 filesystem was introdused:

#include <filesystem>
namespace fs = std::filesystem;

I just add this include and simple call to your lib to test how your CI settings works with it and with c++17 at all.
But I obtain errors in all builds in CI:
fatal error: 'filesystem' file not found
#include <filesystem>
         ^
		 
I created fork from your repo, added it to my Travis and Appveyor, and added this simple commit to my master with filesystem usage.
https://github.com/GillianGrayson/variant
https://travis-ci.org/GillianGrayson/variant
https://ci.appveyor.com/project/GillianGrayson/variant

Can you help me please to fix this issue with CI + c++17 (filesystem)?

Thank you!

**Comment by mpark** [comment]
According to https://en.cppreference.com/w/cpp/compiler_support, it seems like `<filesystem> is available starting GCC 8, and Clang 7. You'll have to remove all of the GCC versions < 8: [`.travis.yml`](https://github.com/GillianGrayson/variant/blob/master/.travis.yml#L26-L59), and remove < C++17 configs from GCC 8: https://github.com/GillianGrayson/variant/blob/master/.travis.yml#L62.

**Comment by mpark** [comment]
The Clang configs don't use libc++ today. It simply uses the default libstdc++. As such, you might need to add `g++-8` as a dependency in your Clang configs.
