### ISSUE TITLE
Update to accepted C++17 paper: P0088R3

### ISSUE THREAD

**Issue by gnzlbg** [mpark/variant#9]
http://wg21.link/p0088r3

**Comment by viboes** [comment]
Don't foget http://wiki.edg.com/pub/Wg21oulu/StrawPolls/P0032R3.pdf

**Comment by mpark** [comment]
Implemented the most recent version of `std::variant` specification.
re: P0032R3, parts of it were superseded by http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0504r0.html
